version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .

  pre_build:
    commands:
      - echo Pre-build phase...
      - apt-get update
      - apt-get install -y zip

  build:
    commands:
      - echo Build started on date
      - echo Packaging the Lambda function...
      - zip -r9 function.zip .

  post_build:
    commands:
      - echo Build completed on date
      - echo Deploying the Lambda function...
      - aws cloudformation package --template-file template.yaml --s3-bucket mystask --output-template-file output-template.yaml
      - aws cloudformation deploy --template-file output-template.yaml --stack-name avinash-demo-stack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - function.zip
    - output-template.yaml
